# Generated by Django 2.2.1 on 2019-06-17 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubLevelConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subLevelName', models.CharField(max_length=300)),
                ('conceptText', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsTest.Level')),
            ],
        ),
        migrations.CreateModel(
            name='SubLevelQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('optionOne', models.TextField()),
                ('optionTwo', models.TextField()),
                ('optionThree', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField()),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('subLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsTest.SubLevelConcepts')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('totalStars', models.IntegerField(default=0)),
                ('badges', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('currentLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentLevel', to='modelsTest.SubLevelConcepts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
