# Generated by Django 2.2.1 on 2019-06-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='date_of_birth',
        ),
    ]
