# Generated by Django 2.2.1 on 2019-06-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0002_remove_learner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='currentLevel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentLevel', to='modelsTest.SubLevelConcepts'),
        ),
    ]
