# Generated by Django 2.2.1 on 2019-06-18 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0004_auto_20190618_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='learner',
            name='currentLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentLevel', to='modelsTest.SubLevelConcepts'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
