# Generated by Django 2.2.1 on 2019-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0006_sublevelquiz_sublevelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublevelquiz',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
