# Generated by Django 2.2.1 on 2019-06-20 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0007_auto_20190620_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublevelquiz',
            name='stars',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
