# Generated by Django 2.2.1 on 2019-06-24 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0010_auto_20190624_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='badges',
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeOne', models.BooleanField(default=False)),
                ('badgeTwo', models.BooleanField(default=False)),
                ('badgeThree', models.BooleanField(default=False)),
                ('badgeFour', models.BooleanField(default=False)),
                ('badgeFive', models.BooleanField(default=False)),
                ('badgeSix', models.BooleanField(default=False)),
                ('badgeSeven', models.BooleanField(default=False)),
                ('badgeEight', models.BooleanField(default=False)),
                ('badgeNine', models.BooleanField(default=False)),
                ('badgeTen', models.BooleanField(default=False)),
                ('badgeEleven', models.BooleanField(default=False)),
                ('badgeTwleve', models.BooleanField(default=False)),
                ('badgeThirteen', models.BooleanField(default=False)),
                ('badgeFourteen', models.BooleanField(default=False)),
                ('badgeFifteen', models.BooleanField(default=False)),
                ('Learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
