# Generated by Django 2.2.1 on 2019-06-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0014_auto_20190625_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badges',
            old_name='badgeTwleve',
            new_name='badgeTwelve',
        ),
    ]
