# Generated by Django 2.2.1 on 2019-06-26 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0015_auto_20190625_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='avatarId',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
