# Generated by Django 2.2.1 on 2019-06-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTest', '0020_auto_20190628_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='currentLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentLevel', to='modelsTest.Level'),
        ),
    ]
